### ISSUE TITLE
Create Verfication and validation template to be filled in at a later date 

### ISSUE THREAD

**Issue by selvatp** [pjmc-oliveira/HubListener#35]
Utilize the templates given by Dr.Smith: 

2. A potential template for verification and validation of your system can be found at:

https://gitlab.cas.mcmaster.ca/smiths/cas741/tree/master/BlankProjectTemplate/docs/VnVPlan/SystVnVPlan

An example System VnV plan (with a few comments from me embedded in it) can be found at:

https://github.com/smiths/caseStudies/blob/master/CaseStudies/ssp/docs/VnVPlan/SystVnVPlan/SystVnVPlan.pdf

to create a custom Validation and Verification document

**Comment by selvatp** [comment]
Completed Template.  @smiths , can you please kindly review this template and let me know if this aligns with what you had in mind. If you believe the structure is good, please go ahead and close the task. 

Thank you.

**Comment by smiths** [comment]
@selvatp, please provide a link to the template in your comment, so I know exactly what document I am supposed to review.

**Comment by selvatp** [comment]
Here you go! I also just pushed the VnV once more after using a spell check.  :)

[`VnV`](https://github.com/pjmc-oliveira/HubListener/blob/master/Doc/Verification%26ValidationPlan/VnVReport/SystVnVReport/SystVnVReport.pdf)

**Comment by smiths** [comment]
@selvatp, the plan looks good, except for the following points:
- You have a section "Changes Due to Testing", but this section doesn't make sense in a plan; Changes due to testing would be part of your report.  The plan says what you are going to do, and the report says how it went
- It is not clear whether you actually plan to list specific test cases.  Testing is a great idea, but you need to do the thinking to figure out what the test cases should be.  Test cases based on your requirements can be written right now.  Test cases related to your design (modules) will have to wait until you have completed your design.

**Comment by selvatp** [comment]
@smiths , Thank you for the feedback. After going through it again, I think I have more questions now.  I would like to go over it with you during our meeting, if possible. 

Changes made : 
-  Deletion of the "Changes Due to Testing" section.
- Added subsections and test case templates for the appropriate sections in hopes that it becomes more clear that we are going to include specific test cases. 

notes: 
1. The team hasn't hashed out what the test cases will be.  We are ongoing with this and will make it a priority for the next possible sprint.  
2.  I added an Appendix for where the Questionnaire will go that will test much of the non-functional requirements. 
3. I will create a separate task for filling out the actual test cases, specifically for the non-functional and functional requirements. T

**Comment by smiths** [comment]
@selvatp, yes, we can discuss this during our meeting.  Some initial thoughts that come to mind:
1. You seem to have a bit of confusion between VnV plan and VnV report.  It is probably feasible for you to write one document that does both jobs, but you should always have a clear picture of what the purpose is for each section.  A plan says that you are going to do and a report says what you did.  The "Changes Due to Testing" section has the purpose in the report of showing the consequences of testing.  This is good information to highlight, since it will show Dr. Anand that you took testing seriously.  
2. I noticed in your LaTeX that you aren't quite following the rules for periods.  If a period appears, but it isn't at the end of a sentence, like in Dr. Anand, you need to tell LaTeX to only leave one space (at the end of a sentence, LaTeX leaves two spaces by default.)  You do this via `Dr.\ Anand`, or `Dr.~Anand'.  The second option makes sure that there are no line breaks between the first and second part of the phrase.
3. More important than the actual template is coming up with meaningful test cases.  It is not too early to think about test cases, for those test cases that are at the system level.  (Unit tests will have to wait until your design is clarified.)
